### ISSUE TITLE
Error in the MFCC baseline

### ISSUE THREAD

**Issue by sameerkhurana10** [bootphon/zerospeech2017#10]
Hi,

When running `./track1/baseline/baseline_one.sh ./data ./track1/baseline/results mandarin 1` i get the following error. I am running inside docker container

```
Traceback (most recent call last):
  File "/zerospeech2017/track1/baseline/../eval/eval_track1.py", line 484, in <module>
    args.normalized, ncpus=ncpus)
  File "/zerospeech2017/track1/baseline/../eval/eval_track1.py", line 357, in fullrun
    distance_file, distancefun, normalized = normalized , n_cpu=ncpus)
  File "/opt/conda/envs/zerospeech/lib/python2.7/site-packages/ABXpy-0.1.0-py2.7-linux-x86_64.egg/ABXpy/distances/distances.py", line 303, in compute_distances
    pool.map(worker, args)
  File "/opt/conda/envs/zerospeech/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/opt/conda/envs/zerospeech/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
KeyError: '569'
Error: cannot evaluate mandarin 1s
```

For english it worked fine

**Comment by sameerkhurana10** [comment]
also for french 1s

```
Opening ./data/test/french/1s/1s_across.abx in read-only mode
/opt/conda/envs/zerospeech/lib/python2.7/site-packages/ABXpy-0.1.0-py2.7-linux-x86_64.egg/ABXpy/distances/metrics/cosine.py:34: VisibleDeprecationWarning: using a boolean instead of an integer will result in an error in the future
  d[i, iy] = 0.
/opt/conda/envs/zerospeech/lib/python2.7/site-packages/ABXpy-0.1.0-py2.7-linux-x86_64.egg/ABXpy/distances/metrics/cosine.py:34: VisibleDeprecationWarning: using a boolean instead of an integer will result in an error in the future
  d[i, iy] = 0.
/opt/conda/envs/zerospeech/lib/python2.7/site-packages/ABXpy-0.1.0-py2.7-linux-x86_64.egg/ABXpy/distances/metrics/cosine.py:34: VisibleDeprecationWarning: using a boolean instead of an integer will result in an error in the future
  d[i, iy] = 0.
/opt/conda/envs/zerospeech/lib/python2.7/site-packages/ABXpy-0.1.0-py2.7-linux-x86_64.egg/ABXpy/distances/metrics/cosine.py:34: VisibleDeprecationWarning: using a boolean instead of an integer will result in an error in the future
  d[i, iy] = 0.
Job 2: computing distances for block 1 on 232
Opening ./data/test/french/1s/1s_across.abx in read-only mode
Job 0: computing distances for block 1 on 230
Opening ./data/test/french/1s/1s_across.abx in read-only mode
Job 3: computing distances for block 1 on 233
Opening ./data/test/french/1s/1s_across.abx in read-only mode
Job 2: computing distances for block 2 on 232
Opening ./data/test/french/1s/1s_across.abx in read-only mode
Traceback (most recent call last):
  File "/zerospeech2017/track1/baseline/../eval/eval_track1.py", line 484, in <module>
    args.normalized, ncpus=ncpus)
  File "/zerospeech2017/track1/baseline/../eval/eval_track1.py", line 357, in fullrun
    distance_file, distancefun, normalized = normalized , n_cpu=ncpus)
  File "/opt/conda/envs/zerospeech/lib/python2.7/site-packages/ABXpy-0.1.0-py2.7-linux-x86_64.egg/ABXpy/distances/distances.py", line 303, in compute_distances
    pool.map(worker, args)
  File "/opt/conda/envs/zerospeech/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/opt/conda/envs/zerospeech/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
KeyError: '18617'
Error: cannot evaluate french 1s
```

**Comment by mmmaat** [comment]
Hi,

For me this is working (in the docker as well). Are you sure you have the rigth data and the correct structure in `/zerospeech2017/data`:
```
  train/
      {english, mandarin, french}/
          *.wav
  test/
      {english, mandarin, french}/
          {1s, 10s, 120s}/
              *.wav
              across.abx
              within.abx
```

**Comment by sameerkhurana10** [comment]
thanks.

The data is downloaded using the `download.sh` script.

Yes, I have the required structure. It worked fine for English.

Does the error `keyerror` mean it could not find the particular wav file? In that case do you have 569.wav in your mandarin test 1s folder? I don't have it.

In my mandarin test 1s folder i have 21249 items. Do you have the same? Trying to figure out if there is something wrong with the download.

**Comment by mmmaat** [comment]
Indeed I have 21250 files and a `569.wav`. 

Here are the MD5 sums for the tar.bz2 you downloaded: 
```
$ md5sum train.tar.bz2 
6b22892f19f2eba092f67467b1d49fc4  train.tar.bz2
$ md5sum test.tar.bz2 
d25c34f23a86a7020218e030ab58929e  test.tar.bz2
$ md5sum train_mandarin.tar.bz2 
e8094f36dab4a2961bdc6c83cd8d1c7a  train_mandarin.tar.bz2
```

**Comment by sameerkhurana10** [comment]
thanks, I will download again.
